//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLUEBOOK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int Book_ID { get; set; }
        public string Book_Name { get; set; }
        public Nullable<System.DateTime> Writing_data { get; set; }
        public Nullable<System.DateTime> Publishing_data { get; set; }
        public Nullable<int> Edition_Number { get; set; }
        public string Language { get; set; }
        public int Category_ID { get; set; }
        public int Author_ID { get; set; }
        public int Publisher_ID { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual Sales Sales { get; set; }
        public virtual Stocks Stocks { get; set; }
        public virtual Publishers Publishers { get; set; }
    }
}
