//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLUEBOOK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int Employee_ID { get; set; }
        public int Store_ID { get; set; }
        public string Employee_FName { get; set; }
        public string Employee_LName { get; set; }
        public string Position { get; set; }
        public string Permission { get; set; }
        public string Password { get; set; }
        public int Age { get; set; }
        public string Address { get; set; }
        public string Phone_Number { get; set; }
    
        public virtual Stores Stores { get; set; }
    }
}
