//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLUEBOOK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.OrdersDetails = new HashSet<OrdersDetails>();
        }
    
        public int Order_Number { get; set; }
        public int Store_ID { get; set; }
        public int Customer_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public string Tender_Type { get; set; }
        public System.DateTime Order_Data { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Stores Stores { get; set; }
        public virtual ICollection<OrdersDetails> OrdersDetails { get; set; }
    }
}
