//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLUEBOOK
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersDetails
    {
        public int Order_Number { get; set; }
        public int Book_ID { get; set; }
        public int Sales_Price { get; set; }
        public int Tax { get; set; }
        public int Discount { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Sales Sales { get; set; }
    }
}
