//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLUEBOOK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publishers
    {
        public Publishers()
        {
            this.Books = new HashSet<Books>();
        }
    
        public int Publisher_ID { get; set; }
        public string Publisher_Name { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Phone_Number { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Books> Books { get; set; }
    }
}
