//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLUEBOOK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocks
    {
        public int Book_ID { get; set; }
        public int Category_ID { get; set; }
        public int Location { get; set; }
        public int Number_of_books { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Categories Categories { get; set; }
    }
}
