//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLUEBOOK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stores
    {
        public Stores()
        {
            this.Employees = new HashSet<Employees>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int Store_ID { get; set; }
        public string Store_Name { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Phone_Number { get; set; }
        public string Email_Address { get; set; }
    
        public virtual ICollection<Employees> Employees { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
